drop table if exists member CASCADE;
create table member (id bigint generated by default as identity, age integer not null, grade varchar(255), name varchar(255), primary key (id));

drop table if exists orders CASCADE;
create table orders (id bigint generated by default as identity, order_price bigint not null, member_id bigint, primary key (id));